
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: ["air"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
